### ISSUE TITLE
Null Pointer Exception Occurs When Searching for "dna repair"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [PathwayCommons/cpath2#19]
```
What steps will reproduce the problem?
1.  I searched for "dna repair"  

What is the expected output? What do you see instead?

I got a NullPointerException:

java.lang.NullPointerException
    at
org.apache.jsp.WEB_002dINF.jsp.pages.search.biopax_005fsearch_jsp._jspService(bi
opax_005fsearch_jsp.java:364)
    at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:94)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:856)


What version of the product are you using? On what operating system?


Please provide any additional information below.

```

Original issue reported on code.google.com by `cer...@gmail.com` on 2 Oct 2009 at 1:23

**Comment by IgorRodchenkov** [comment]
This issue was moved to PathwayCommons/cpath1#23
