### ISSUE TITLE
A Neighborhood query fails when format is SBGN

### ISSUE THREAD

**Issue by IgorRodchenkov** [PathwayCommons/cpath2#321]
I guess it's a new issue - has to do with SBGN format only...
```
curl -X 'GET'   'https://www.pathwaycommons.org/pc2/graph?source=ANK1&source=PTEN&limit=1&format=SBGN&kind=NEIGHBORHOOD&message=true'   -H 'accept: */*'
{"timestamp":1720128609764,"status":500,"error":"Internal Server Error","message":"500; Internal Server Error - java.lang.NullPointerException: Cannot invoke \"org.sbgn.bindings.Port.getId()\" because \"target\" is null; [org.biopax.paxtools.io.sbgn.L3ToSBGNPDConverter.createArc(L3ToSBGNPDConverter.java:1300), org.biopax.paxtools.io.sbgn.L3ToSBGNPDConverter.processControllers(L3ToSBGNPDConverter.java:365), org.biopax.paxtools.io.sbgn.L3ToSBGNPDConverter.createSBGN(L3ToSBGNPDConverter.java:317), org.biopax.paxtools.io.sbgn.L3ToSBGNPDConverter.writeSBGN(L3ToSBGNPDConverter.java:239), cpath.service.BiopaxConverter.convertToSBGN(BiopaxConverter.java:167), cpath.service.BiopaxConverter.convert(BiopaxConverter.java:86), cpath.service.BiopaxConverter.convert(BiopaxConverter.java:135), cpath.service.ServiceImpl.convert(ServiceImpl.java:365), cpath.service.ServiceImpl.getNeighborhood(ServiceImpl.java:259), cpath.web.ApiControllerV1.graphQuery(ApiControllerV1.java:223), cpath.web.ApiControllerV1.graphQueryGet(ApiControllerV1.java:190), java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103), java.base/java.lang.reflect.Method.invoke(Method.java:580), org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:255), org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:188), org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118), org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:925), org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:830), org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87), org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089), org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979), org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014), org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903), jakarta.servlet.http.HttpServlet.service(HttpServlet.java:527), org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885), jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614), org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205), org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149), org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51), org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174), org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149), org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:109), org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116), org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174), org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149), org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201), org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116), org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174), org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149), org.springframework.web.filter.ForwardedHeaderFilter.doFilterInternal(ForwardedHeaderFilter.java:173), org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116), org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174), org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149), org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167), org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90), org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482), org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115), org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93), org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74), org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344), org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391), org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63), org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896), org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744), org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52), org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191), org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659), org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63), java.base/java.lang.Thread.run(Thread.java:1583)]","path":"/pc2/graph"}
```

_Originally posted by @IgorRodchenkov in https://github.com/PathwayCommons/cpath2/issues/320#issuecomment-2209581420_

This seems some old Paxtools L3ToSBGNPDConverter bug that occurs now as we have new data in PC2...
If we just remove format=SBGN it returns BioPAX data/model just fine (other formats also work).
So we likely need to debug Paxtools (v6.0.0, 6.0.1-SNAPSHOT) sbgn-converter module using these new example data...  

Also, this error can be reproduced with just one source=PTEN (but not with just source=ANK1 or e.g. PCNA or smth....)

**Comment by IgorRodchenkov** [comment]
Did some local debugging with just Paxtools sbgn-converter and the BioPAX data from query: `https://www.pathwaycommons.org/pc2/graph?source=ANK1&source=PTEN&limit=1&kind=NEIGHBORHOOD` 

The error only happens there when I use the blacklist.txt (file from `https://www.pathwaycommons.org/downloads/blacklist.txt`) with L3ToSBGNPDConverter (no errors when null or simple test/nonsense blacklist is used instead):
```
java.lang.AssertionError: target = null

	at org.biopax.paxtools.io.sbgn.L3ToSBGNPDConverter.createArc(L3ToSBGNPDConverter.java:1290)
	at org.biopax.paxtools.io.sbgn.L3ToSBGNPDConverter.processControllers(L3ToSBGNPDConverter.java:365)
	at org.biopax.paxtools.io.sbgn.L3ToSBGNPDConverter.createSBGN(L3ToSBGNPDConverter.java:317)
	at org.biopax.paxtools.io.sbgn.L3ToSBGNPDConverter.writeSBGN(L3ToSBGNPDConverter.java:225)
	at org.biopax.paxtools.io.sbgn.SBGNConverterTest.convertPc14NearestNeighborhoodOfANK1_PTEN(SBGNConverterTest.java:398)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```
- this is pretty the same error as what happens internally in case the HTTP query with format=SBGN is used, but it's AssertionError that points to L3ToSBGNPDConverter.java line 1290 instead of NullPointerException at line 1300 due to java assertions on likes 1289-1290 (`assert ...`) are disabled there in production server.
